name: Latest blog post workflow
on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://arshnoor.hashnode.dev/rss.xml,https://medium.com/feed/@arshnoorsinghsohi"
          max_post_count: 5
          commit_message: "Updated with latest blog posts"
          committer_username: "blog-post-bot"
          committer_email: "blog-post-bot@users.noreply.github.com"